### PR TITLE
Implement add new event command

### PR DESCRIPTION
**Pull request by ChengYuuu**
Attempt to morph existing add command to a add event command.
New events can only be either 
(1) Single events
(2) Repeated Daily
(3) Repeated Weekly
(4) Repeated Monthly
(5) Repeated Yearly

### CODE REVIEW

**Comment by HEARTOFAL1ON** [comment]
How is it @ChengYuuu ? Still can't really get all tests to pass? :( Actually, my suggestion is to click on the Codacy/PR Quality Review and see where you can improve :) (hopefully can see when clicking on the link ahh)

**Comment by HEARTOFAL1ON** [comment]
image

Anyone knows how to resolve this?

**Comment by ChengYuuu** [comment]
wait. I haven't wrote the test cases yet. Unless you want to merge without unit testing?

**Comment by HEARTOFAL1ON** [comment]
Good point! Okay then it's better to merge after testing I guess.

**Comment by YezhongZ** [comment]
Yea I think we can merge first.

**Pull request merged**
