### PR TITLE
Resolve merge conflicts

### PR DESCRIPTION
**Pull request by HEARTOFAL1ON**

### CODE REVIEW

**Comment by YezhongZ** [comment]
Do you mind to unstage them for this PR?
or
Can you justify their purpose for this PR?

**Comment by YezhongZ** [comment]
> Why are we doing this? Why do we have multiple gh-pages branch?

The curent gh-pages is protected and cannot be edited directly.
Daniel created a normal branch for PR to fix some issue. The name of the PR branch is a bit confusing, but it is just a normal branch (can be any name).

**Comment by ChengYuuu** [comment]
if you want to create a pr, why don't you use the forked branch from your own local repo and create a pr? Why are we creating a branch on team-org repo and pr-ing from that branch?

**Comment by ChengYuuu** [comment]
Also what is this change about? Why are we editing the gh pages?

**Comment by HEARTOFAL1ON** [comment]
I created another branch which is nothing to do wif the `gh-pages` branch

**Comment by ChengYuuu** [comment]
Tbh I don't really know which workflow are we following now? Are we going to interact with team repo directly? or are we going to use the forking workflow? Because from what I see now, you are using the branching workflow.

**Comment by HEARTOFAL1ON** [comment]
Let's just close this first

**Pull request closed without merging**
